### PR TITLE
Desi legacy survey

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — COMMENTED** [review]
it's strange but ok.

but what was returning 500?..

**Comment by dsavchenko** [comment]
I am trying to use it and get an error
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_80552/894788455.py in <module>
----> 1 query=DESILegacySurvey.get_images(coordinates='icrs', radius=image_size, pixels=npix, survey='dr%d'%dr, position=source)
      2 
      3 hdul = file.get_fits()
      4 hdul[0].header

~/Projects/cloud/legacysurvey/legacysurvey-backend/.venv/src/astroquery/astroquery/utils/class_or_instance.py in f(*args, **kwds)
     23         def f(*args, **kwds):
     24             if obj is not None:
---> 25                 return self.fn(obj, *args, **kwds)
     26             else:
     27                 return self.fn(cls, *args, **kwds)

~/Projects/cloud/legacysurvey/legacysurvey-backend/.venv/src/astroquery/astroquery/utils/process_asyncs.py in newmethod(self, *args, **kwargs)
     27             if kwargs.get('get_query_payload') or kwargs.get('field_help'):
     28                 return response
---> 29             result = self._parse_result(response, verbose=verbose)
     30             self.table = result
     31             return result

~/Projects/cloud/legacysurvey/legacysurvey-backend/.venv/src/astroquery/astroquery/desi/core.py in _parse_result(self, responses, verbose)
    359 
    360             for r in responses:
--> 361                 if r.status_code == 200:
    362                     # TODO figure out on how to avoid writing in a file
    363                     with open('/tmp/file_content', 'wb') as fin:

AttributeError: 'HDUList' object has no attribute 'status_code'
```

**Comment by burnout87** [comment]
> I am trying to use it and get an error

Can you try again now?

>       2 
>       3 hdul = file.get_fits()


This will no longer be necessary since the function returns a list of of `HDUList` objects, so this step is already performed.

**Comment by burnout87** [comment]
> 
> but what was returning 500?..

The extraction of the fits file from the `FileContainer` object was returning a `500` error:

``` Python
hdul = file.get_fits()
```

I noticed how only the `cadc` service handles this situation, though in a different way:

[https://github.com/oda-hub/astroquery/blob/3d88b538c7e5000f4784e1ea4271d2bbf35d98b9/astroquery/cadc/core.py#L354-L361](https://github.com/oda-hub/astroquery/blob/3d88b538c7e5000f4784e1ea4271d2bbf35d98b9/astroquery/cadc/core.py#L354-L361)

**Comment by volodymyrss** [comment]
would be useful to have a test with this 500 .

**Review by dsavchenko — APPROVED** [review]

**Review by volodymyrss — APPROVED** [review]

**Pull request merged**
